AllCops:
  TargetRubyVersion: "2.5"
  NewCops: enable

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
Metrics/MethodLength:
  Max: 20

Naming/FileName:
  Exclude:
    - lib/grape-kaminari.rb

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
